"""Deterministic CSL reference rendering (home-grown, no citeproc-py dependency).

This module is what makes citeformer's "references are never generated by the
LLM" promise real. Home-grown formatters (`citeformer.render.formatters`)
consume `Source.metadata` (CSL-JSON) and render both the inline marker and
the full bibliography entry. The model is never involved.

Public API:

- `render_references(sources, citations, style)` — produce the `Reference`
  list for a generation call.
- `render_single_reference(source, style_name)` — convenience helper.
- `get_formatter(name)` — look up a `CitationFormatter` directly.
- `bundled_style_names()` — list of built-in styles.
- `style_citation_format(name)` — classify a style (author-date / author /
  numeric / note / label).
"""

from __future__ import annotations

from citeformer.render.csl import render_references, render_single_reference
from citeformer.render.formatters import (
    Author,
    CitationFormatter,
    available_formatters,
    get_formatter,
)
from citeformer.render.styles import bundled_style_names, style_citation_format

__all__ = [
    "Author",
    "CitationFormatter",
    "available_formatters",
    "bundled_style_names",
    "get_formatter",
    "render_references",
    "render_single_reference",
    "style_citation_format",
]
