"""Deterministic CSL reference rendering.

This module is what makes citeformer's "references are never generated by the
LLM" promise real. `citeproc-py` consumes `Source.metadata` (CSL-JSON) and
renders both the inline marker and the full bibliography entry in any CSL
style. The model is never involved.

Public API:

- `render_references(sources, citations, style)` — produce the `Reference`
  list for a generation call.
- `load_style(name_or_path)` — cached style loader; accepts bundled names or
  filesystem paths.
- `bundled_style_names()` — list of known-good styles shipped with the package.
- `style_citation_format(name_or_path)` — classify a style as `author-date` /
  `numeric` / `note` / `label` without rendering.
"""

from __future__ import annotations

from citeformer.render.csl import render_references
from citeformer.render.styles import (
    bundled_style_names,
    load_style,
    resolve_style_path,
    style_citation_format,
)

__all__ = [
    "bundled_style_names",
    "load_style",
    "render_references",
    "resolve_style_path",
    "style_citation_format",
]
